### PR TITLE
Fux Division Runtime Errors

### PR DESCRIPTION
**Pull request by ben-burwood**
Hi, 
Nice work on this, really useful tool!

I have fixed a couple of RunTimeErrors that occurred due to unspecified arithmetic.
Also refactored slightly to make the Constants clear and added TypeHints to make the Functions easier to understand.
Addition of input to use alongside CLI arguments - not currently implemented.

### CODE REVIEW

**Comment by wozniakpawel** [comment]
Hi @benbur98 ! Appreciate the PR, and I would love to merge just the division runtime error fixes, but there is a lot more going on in the commits.
Can you somehow isolate the division error fixes, possibly on a separate branch, and raise a PR again? Or, you could revert some of the commits if you prefer.
Code refactor is a different thing and I'd like to keep them separate.
CLI argument changes don't make sense until they're actually working.

**Comment by crossland92** [comment]
I've got some local changes going on too for:

- Handling Student Loan Plan 1
- Handling pension contributions from the command line
- Fixing a bug with 'take_home_amount' not accounting for pension contributions

Can pop up in the next couple of days!

**Comment by wozniakpawel** [comment]
Hi @benbur98 are you planning to separate the division runtime error fixes? I'd like to give credit where it's due 👍🏻 

@crossland92 sounds really good! Looking forward to the PR.

**Comment by benbur98** [comment]
Hi @wozniakpawel , I'm not gunna have any time to work on this for a while now. Feel free to take anything you want and can close the PR :)

**Pull request closed without merging**
